### ISSUE TITLE
Transparent Skins

### ISSUE THREAD

**Issue by ghost** [minotar/minecraft#21]
In 1.9+ Minecraft introduced transparent Skins your API doesn't handle this
![image](https://user-images.githubusercontent.com/37674069/167512481-10d3814f-699c-4131-b206-9e2ac59aec9f.png)
What it should look like
![image](https://user-images.githubusercontent.com/37674069/167512509-59d39858-d4bb-46eb-a95f-2c8d3a38147d.png)

**Comment by LukeHandle** [comment]
Interesting! There had been previous reports of occasional issues with the overlays, but the pixel transparency would make sense as the cause.

The current logic is here for how the layer is applied https://github.com/minotar/imgd/blob/f51c98c9dc1ae19069cfe5c9b0be778b299cc054/process.go#L346-L363

I'd expect it's a case of calculating the backing colour based on the transparent layer applied.

Do you have the original skin available to upload?

**Comment by ghost** [comment]
![Texture](https://textures.minecraft.net/texture/12c1f8209f8fca058cad6bfc117623c8df404cbd4eb6e0cbeb5645a551b43ece)

im not really good at go but i assume the issue is here since the skin is partially transparent we dont want to set it 0
```go
if skin.AlphaSig[3] == 0 {
		return
}
```

**Comment by 1fxe** [comment]
I tried to port how mc handles this in go 
https://gist.github.com/1fxe/882ba114ad2a8c836c0a010a36c5eca4
It keeps transparency but doesnt fill in all the black area because to much work for me atm

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/37674069/167523658-d54d8857-e5ec-4899-bb05-dc8d24074d47.png)
Almost fixed it

**Comment by LukeHandle** [comment]
Thanks for your work on this, now resolved per https://github.com/minotar/imgd/pull/215
